### ISSUE TITLE
Wrong Artifact in Newpipe-19 Fork ReleaseTag19.9.6

### ISSUE THREAD

**Issue by ShareASmile** [Isayso/VideoLinkSafe#2]
I tried Newpipe19 Release Tag v19.9.6 latest apk (with fix comments parsing extractor 20.6) but unfortunately it is not playing any youtube  video.

It shows version NewPipe 19.9 Isayso Fork 11/29/20 instead of v19.9.6. Would you please  Reupload correct working version 19.9.6 with fix comments parsing. Thanks in advance.

As Issue tracker not being available in NewPipe19 fork so i am commenting here. Apologies for that.

**Comment by Isayso** [comment]
I will do that. Not playing any video? I tested it on my Android 9 phone. 
What version do you have?
I activated the issue tracker now.

**Comment by Isayso** [comment]
Updated it right now!

**Comment by ShareASmile** [comment]
> What version do you have?
 
I have Samsung J2 Pro SM-J210F Running on Android 6.0.1. Earlier 19.9.4 build (7.4Mb) with Multidex & Desugar was running fine on my phone untill comments parsing error started happening on every video! 

Can confirm NewPipe v19.9.6 v2(variant) build with better support for older Android versions works fine on my device. Video plays fine, comments load fine. Thanks @Isayso You Rock✌

**Comment by Isayso** [comment]
Thanks for your feedback. I had lots of problems with desugaring on my device. Will do 2 versions in the future.
